application: fortune-teller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: templates/css

#static directories should go ABOVE the catch all url (.*)
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
#add jinja2 here, remember in .yaml files, white space is important
- name: jinja2
  version: latest
